[mypy]
python_version = 3.11
warn_return_any = True
warn_unused_configs = True
ignore_missing_imports = True

[mypy-config_manager]
ignore_errors = True

[mypy-job_discovery.*]
ignore_errors = True

[mypy-logging_config]
ignore_errors = True

[mypy-tracking.*]
ignore_errors = True

[mypy-rich.*]
ignore_errors = True
