name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install and Run Pre-Commit
        run: |
          pip install uv
          uv venv
          source .venv/bin/activate
          uv pip install -e ".[test,lint]"
          uv pip install -r requirements.txt
          pre-commit run --all-files

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest --ignore=tests/test_indeed_scraper_integration.py --ignore=tests/test_reed_scraper_integration.py --ignore=tests/test_scrapers_integration.py --ignore=tests/test_stackoverflow_scraper_integration.py --ignore=tests/test_totaljobs_scraper_integration.py
